# Generated by Django 4.2.6 on 2023-10-31 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionableModel',
            fields=[
                ('item_name', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('item_price_bid', models.IntegerField()),
                ('item_highest_price', models.IntegerField()),
                ('item_quatity', models.IntegerField()),
                ('item_image', models.ImageField(default='https://sm.mashable.com/t/mashable_sea/photo/default/man-fakes-death-cat-q6u_2z9w.2496.png', upload_to='')),
                ('item_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionableBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_bid_amount', models.IntegerField()),
                ('bidder_email', models.EmailField(max_length=254)),
                ('item_description', models.TextField(max_length=500)),
                ('item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
