# Generated by Django 4.2.6 on 2023-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionablemodel',
            name='item_image',
            field=models.TextField(),
        ),
    ]
