# Generated by Django 4.2.3 on 2023-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionables', '0002_alter_auctionablemodel_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionablemodel',
            name='item_image',
            field=models.ImageField(default='https://sm.mashable.com/t/mashable_sea/photo/default/man-fakes-death-cat-q6u_2z9w.2496.png', upload_to=''),
        ),
    ]
